### ISSUE TITLE
Where do comments go?

### ISSUE THREAD

**Issue by whatsnewsaes** [scalableminds/time-tracker#80]
Really enjoying time tracker.

One questions i have -- where does the "comment" go after you log time?

Also is it possible to give an admin control to see an overview of all tasks worked on?

<a href="https://timer.scm.io/repos/537238621a000061003c4a1e/issues/80/create?referer=github" target="_blank">Log Time</a>

**Comment by hotzenklotz** [comment]
Hi. We are glad that you like the time tracker.

1. Comments are not shown anywhere at the moment. I believe it used to be that you could hover over any time entry and they were shown, but no more.
2. I am not quite sure I understand the task overview thing. If you simply want to see all your tasks, why don't you just look at the Github issues? You can even filter the issue more fine-grained in the GH interface, e.g. only look for one person. Does that satisfy your needs?

In any case feel free to send us a PR for additional features. :-)

**Comment by whatsnewsaes** [comment]
for #2 I meant something that we could give to our office manager to be able to look at and invoice from across our whole company, rather than just seeing my individual tasks. I like the ability to see the "team" but that doesn't give the ability to see what task each person worked on, but rather which project they're recording their time against.

**Comment by hotzenklotz** [comment]
I suppose it would be nice to be able to have a button that extends every project to show it's tasks. However, we are not planning on adding this feature any time soon. Feel free to file a PR and I will merge it.

**Comment by whatsnewsaes** [comment]
Thanks @hotzenklotz!
