### ISSUE TITLE
Log time link is incorrect

### ISSUE THREAD

**Issue by daniel-wer** [scalableminds/time-tracker#86]
The Log Time link in an issue looks like this for me currently:

`http://0.0.0.0:9000/repos/537237ce1a00001a003c4a14/issues/1389/create?referer=github`

<a href="http://0.0.0.0:9000/repos/537238621a000061003c4a1e/issues/86/create?referer=github" target="_blank">Log Time</a>

**Comment by normanrz** [comment]
looks like a simple configuration issue that could be fixed with: `host.url="https://timer.scm.io"`
