### ISSUE TITLE
CircleCI build broken

### ISSUE THREAD

**Issue by jstriebel** [scalableminds/time-tracker#94]
CircleCI is not building anymore what used to work, see [build 35](https://circleci.com/gh/scalableminds/time-tracker/35) and [build 43](https://circleci.com/gh/scalableminds/time-tracker/43).

Error happens during ` docker-compose run time-tracker-webpack`:
```
npm ERR! path /project/node_modules/.staging/webpack-sources-d685cf5b
npm ERR! code EINVAL
npm ERR! errno -22
npm ERR! syscall chown
npm ERR! EINVAL: invalid argument, chown '/project/node_modules/.staging/webpack-sources-d685cf5b'
```

<a href="https://timer.scm.io/repos/537238621a000061003c4a1e/issues/94/create?referer=github" target="_blank">Log Time</a>

**Comment by normanrz** [comment]
Looks like the mode is missing. maybe that is a webpack bug or something. I remember having this problem before; but don't know where anymore
